
****************************************************************************
***                       Sentaurus Workbench gjob                       ***
***                          Version V-2024.03                           ***
***                      (3.8727837, x86_64, Linux)                      ***
***                                                                      ***
***                Copyright (c) 1994-2024 Synopsys, Inc.                ***
***                                                                      ***
***  This software and the associated documentation are confidential     ***
***  and proprietary to Synopsys, Inc.  Your use or disclosure of this   ***
***  software is subject to the terms and conditions of a written        ***
***  license agreement between you, or your company, and Synopsys, Inc.  ***
****************************************************************************

gjob is running on host 'kdplab01' by user 'aknicholas'
Binary '/code/Synopsys/tcad_sentaurus_vV-2024.03/sentaurus/current/bin/../tcad/current/linux64/bin/gjob'
Command line options '-verbose -nice 19 -job 1 -swb_pid 3837877 -gsub_pid 3838808 -gsub_host kdplab01 -gsub_port 39313 /home/aknicholas/DB/smartPixTCAD-main/dot1_50x13_phase3_updated/smartpix'
Current directory '/home/aknicholas/DB/smartPixTCAD-main/dot1_50x13_phase3_updated/smartpix'
Project organization 'Traditional'
Some relevant environment variables:
	STROOT=/code/Synopsys/tcad_sentaurus_vV-2024.03/sentaurus/current/bin/..
	STRELEASE=current
	STROOT_LIB=/code/Synopsys/tcad_sentaurus_vV-2024.03/sentaurus/current/bin/../tcad/current/lib
	STDB=/home/aknicholas/DB
	DATEX=/code/Synopsys/tcad_sentaurus_vV-2024.03/sentaurus/current/bin/../tcad/current/lib/datexcodes.txt
	DISPLAY=localhost:10.0

Project '/home/aknicholas/DB/smartPixTCAD-main/dot1_50x13_phase3_updated/smartpix'
INITIALIZING PREPROCESSOR:
Application mode : traditional
Loading project tree '/home/aknicholas/DB/smartPixTCAD-main/dot1_50x13_phase3_updated/smartpix/gtree.dat'
Loading jobs and dependence graph '"/home/aknicholas/DB/smartPixTCAD-main/dot1_50x13_phase3_updated/smartpix/gexec.cmd"'
Loading project variables '/home/aknicholas/DB/smartPixTCAD-main/dot1_50x13_phase3_updated/smartpix/gvars.dat'
--Get files to preprocess...
--Create file handlers...
--Read the toolflow...
--Analyze tool-file dependencies...
--Read all nodes to preprocess...
--Group nodes into experiments...
--Get all variables...
--Get all parameters...
PREPROCESSOR SUCCESSFULLY INITIALIZED.
PREPROCESSING STEP 1:
Reading file /home/aknicholas/DB/smartPixTCAD-main/dot1_50x13_phase3_updated/smartpix/sde_dvs.cmd
Reading file /home/aknicholas/DB/smartPixTCAD-main/dot1_50x13_phase3_updated/smartpix/sde_epi.csv
PREPROCESSING STEP 2:
---------------------------------------
Preprocessing file /home/aknicholas/DB/smartPixTCAD-main/dot1_50x13_phase3_updated/smartpix/sde_dvs.cmd for node 1
+++Preprocessing results written to /home/aknicholas/DB/smartPixTCAD-main/dot1_50x13_phase3_updated/smartpix/pp1_dvs.cmd
---------------------------------------
Preprocessing file /home/aknicholas/DB/smartPixTCAD-main/dot1_50x13_phase3_updated/smartpix/sde_epi.csv for node 1
+++Preprocessing results written to /home/aknicholas/DB/smartPixTCAD-main/dot1_50x13_phase3_updated/smartpix/pp1_dvs.csv
Executing 'sde' binary in original user environment
Start Simulation section
15:24:57 Jan 20 2025     job 1 <sde> started on host 'kdplab01': "sde -e -l n1_dvs.cmd"
15:25:00 Jan 20 2025 +++ job 1 <sde> done: exit(0)
End Simulation section
Start Epilogue section
15:25:00 Jan 20 2025 *** job 1 pre/post execution: eval " gjob::find_extracted_vars "/home/aknicholas/DB/smartPixTCAD-main/dot1_50x13_phase3_updated/smartpix" n1_dvs.out 1 "
End Epilogue section
Job succeeded
gjob exits with status 0
